const data = [
	{
		name: 'Richard Feynman',
		born: 1918,
		died: 1988,
		img: 'richard-feynman.jpg',
		category: 'science',
	},
	{
		name: 'Leonhard Euler',
		born: 1707,
		died: 1783,
		img: 'Leonhard_Euler.jpg',
		category: 'science',
	},
	{
		name: 'Carl Friedrich Gauss',
		born: 1777,
		died: 1855,
		img: 'Carl_Friedrich_Gauss.jpg',
		category: 'science',
	},
	{
		name: 'Fritz Haber',
		born: 1868,
		died: 1934,
		img: 'Fritz_Haber.png',
		category: 'science',
	},
	{
		name: 'Carl Sagan',
		born: 1934,
		died: 1996,
		img: 'Carl_Sagan.png',
		category: 'science',
	},
	{
		name: 'George Washington',
		born: 1732,
		died: 1799,
		img: 'George_Washington.jpg',
		category: 'politics',
	},
	{
		name: 'Thomas Jefferson',
		born: 1743,
		died: 1826,
		img: 'Thomas_Jefferson.jpg',
		category: 'politics',
	},
	{
		name: 'Thomas Paine',
		born: 1737,
		died: 1809,
		img: 'Thomas_Paine.jpg',
		category: 'politics',
	},
	{
		name: 'Albert Einstein',
		born: 1879,
		died: 1955,
		img: 'Albert Einstein.jpg',
		category: 'science',
	},
	{
		name: 'Benjamin Franklin',
		born: 1706,
		died: 1790,
		img: 'Benjamin Franklin.jpg',
		category: 'politics',
	},
	{
		name: 'Kurt G&ouml;del',
		born: 1906,
		died: 1978,
		img: 'Kurt_godel.jpg',
		category: 'science',
	},
	{
		name: 'Franz Kafka',
		born: 1883,
		died: 1924,
		img: 'Franz_Kafka.jpg',
		category: 'arts',
	},
	{
		name: 'Amelia Earhart',
		born: 1897,
		died: 1939,
		img: 'Amelia_Earhart.jpg',
		category: 'explorers',
	},
	{
		name: 'Charles Lindbergh',
		born: 1902,
		died: 1974,
		img: 'Charles Lindbergh.jpg',
		category: 'explorers',
	},
	{
		name: 'Sir Edmund Hillary',
		born: 1919,
		died: 2008,
		img: 'Edmund_Hillary.jpg',
		category: 'explorers',
	},
	{
		name: 'Thor Heyerdahl',
		born: 1914,
		died: 2002,
		img: 'ThorHeyerdahl.jpg',
		category: 'explorers',
	},
	{
		name: 'David Livingstone',
		born: 1813,
		died: 1873,
		img: 'david-livingstone.jpg',
		category: 'explorers',
	},
	{
		name: 'Charlie Chaplin',
		born: 1889,
		died: 1977,
		img: 'Charlie_Chaplin.jpg',
		category: 'arts',
	},
	{
		name: 'Cary Grant',
		born: 1904,
		died: 1986,
		img: 'Cary Grant.jpg',
		category: 'arts',
	},
	{
		name: 'Mahatma Gandhi',
		born: 1869,
		died: 1948,
		img: 'mahatma-gandhi.jpg',
		category: 'politics',
	},
	{
		name: 'Ginger Rogers',
		born: 1911,
		died: 1995,
		img: 'Ginger_Rogers.jpg',
		category: 'arts',
	},
	{
		name: 'Fred Astaire',
		born: 1899,
		died: 1987,
		img: 'Fred Astaire.jpg',
		category: 'arts',
	},
	{
		name: 'Groucho Marx',
		born: 1890,
		died: 1977,
		img: 'Groucho_Marx.jpg',
		category: 'arts',
	},
	{
		name: 'Karl Marx',
		born: 1818,
		died: 1883,
		img: 'Karl_Marx.jpg',
		category: 'politics',
	},
	{
		name: 'Vladimir Lenin',
		born: 1870,
		died: 1924,
		img: 'vladimir-lenin.jpg',
		category: 'politics',
	},
	{
		name: 'Catherine the Great (Catherine II)',
		born: 1729,
		died: 1796,
		img: 'catherine-the-great.jpg',
		category: 'politics',
	},
	{
		name: 'Nikolai II Alexandrovich Romanov',
		born: 1868,
		died: 1918,
		img: 'Nikolai II Alexandrovich Romanov.jpg',
		category: 'politics',
	},
	{
		name: 'Anne Frank',
		born: 1929,
		died: 1945,
		img: 'Anne_Frank.jpg',
		category: 'arts',
	},
	{
		name: 'Nikola Tesla',
		born: 1856,
		died: 1943,
		img: 'Nikola Tesla.jpeg',
		category: 'science',
	},
	{
		name: 'Igor Stravinsky',
		born: 1882,
		died: 1971,
		img: 'Igor_Stravinsky.jpg',
		category: 'arts',
	},
	{
		name: 'Ernest Hemingway',
		born: 1899,
		died: 1961,
		img: 'hemingway-800x800.jpg',
		category: 'arts',
	},
	{
		name: 'Tennessee Williams',
		born: 1911,
		died: 1983,
		img: 'Tennessee_Williams.jpg',
		category: 'arts',
	},
	{
		name: 'George Orwell',
		born: 1903,
		died: 1950,
		img: 'George_Orwell.jpg',
		category: 'arts',
	},
	{
		name: 'Jane Austen',
		born: 1775,
		died: 1817,
		img: 'Jane-Austen.jpg',
		category: 'arts',
	},
	{
		name: 'Franklin D. Roosevelt',
		born: 1882,
		died: 1945,
		img: 'FDR.jpg',
		category: 'politics',
	},
	{
		name: 'John F. Kennedy',
		born: 1917,
		died: 1963,
		img: 'JFK.jpg',
		category: 'politics',
	},
	{
		name: 'Abraham Lincoln',
		born: 1809,
		died: 1865,
		img: 'Abraham_Lincoln.jpg',
		category: 'politics',
	},
	{
		name: 'Queen Victoria',
		born: 1819,
		died: 1901,
		img: 'Queen_Victoria.jpg',
		category: 'politics',
	},
	{
		name: 'Napoleon Bonaparte',
		born: 1769,
		died: 1821,
		img: 'Napoleon Bonaparte.jpg',
		category: 'politics',
	},
	{
		name: 'Greta Garbo',
		born: 1905,
		died: 1990,
		img: 'Greta_Garbo.jpg',
		category: 'arts',
	},
	{
		name: 'James Dean',
		born: 1931,
		died: 1955,
		img: 'James_Dean.jpg',
		category: 'arts',
	},
	// {
	// 	name: 'Voltaire (Fran&ccedil;ois-Marie Arouet)',
	// 	born: 1694,
	// 	died: 0,
	// 	img: '',
	// 	category: 'arts',
	// },
	{
		name: 'Pierre-Auguste Renoir',
		born: 1841,
		died: 1919,
		img: 'Pierre_Auguste_Renoir.jpg',
		category: 'arts',
	},
	{
		name: 'Pablo Picasso',
		born: 1881,
		died: 1973,
		img: 'Pablo-Picasso.jpg',
		category: 'arts',
	},
	{
		name: 'Claude Monet',
		born: 1840,
		died: 1926,
		img: 'Claude_Monet.jpg',
		category: 'arts',
	},
	{
		name: 'Claude Debussy',
		born: 1862,
		died: 1918,
		img: 'Claude_Debussy.jpg',
		category: 'arts',
	},
	{
		name: 'Audrey Hepburn',
		born: 1929,
		died: 1993,
		img: 'Audrey_Hepburn.jpg',
		category: 'arts',
	},
	{
		name: 'Louis XVI',
		born: 1754,
		died: 1793,
		img: 'louis-xvi.jpg',
		category: 'politics',
	},
	{
		name: 'Jonas Salk',
		born: 1914,
		died: 1995,
		img: 'Jonas_Salk.jpg',
		category: 'science',
	},
	{
		name: 'Alan Turing',
		born: 1912,
		died: 1954,
		img: 'Alan_Turing.jpg',
		category: 'science',
	},
	{
		name: 'Marcel Proust',
		born: 1871,
		died: 1922,
		img: 'Marcel_Proust.jpg',
		category: 'arts',
	},
	{
		name: 'Henri Poincar&eacute;',
		born: 1854,
		died: 1912,
		img: 'Henri_Poincare.png',
		category: 'science',
	},
	{
		name: 'Henry David Thoreau',
		born: 1817,
		died: 1862,
		img: 'Henry_David_Thoreau.jpg',
		category: 'arts',
	},
	{
		name: 'Johann Wolfgang von Goethe',
		born: 1749,
		died: 1832,
		img: 'Goethe.jpg',
		category: 'science',
	},
	{
		name: 'Bertrand Russell',
		born: 1872,
		died: 1970,
		img: 'Bertrand_Russell.jpg',
		category: 'science',
	},
	{
		name: 'Sigmund Freud',
		born: 1856,
		died: 1939,
		img: 'Sigmund-Freud.jpg',
		category: 'science',
	},
	{
		name: 'Marie Curie',
		born: 1867,
		died: 1934,
		img: 'Marie_Curie.jpg',
		category: 'arts',
	},
	{
		name: 'Andrew Jackson',
		born: 1767,
		died: 1845,
		img: 'andrew_jackson.jpg',
		category: 'politics',
	},
	{
		name: 'Margaret Thatcher',
		born: 1925,
		died: 2013,
		img: 'Margaret Thatcher.jpg',
		category: 'politics',
	},
	{
		name: 'Joseph Stalin',
		born: 1878,
		died: 1953,
		img: 'Stalin.jpg',
		category: 'politics',
	},
	{
		name: 'Adolf Hitler',
		born: 1889,
		died: 1945,
		img: 'Hitler.jpg',
		category: 'politics',
	},
	{
		name: 'Mao Zedong',
		born: 1893,
		died: 1976,
		img: 'Mao_Zedong.jpg',
		category: 'politics',
	},
	{
		name: 'Hirohito (Emperor Sh&omacr;wa)',
		born: 1901,
		died: 1989,
		img: 'Hirohito.jpg',
		category: 'politics',
	},
	{
		name: 'Sim&oacute;n Bol&iacute;var',
		born: 1783,
		died: 1830,
		img: 'simon-bolivar.jpg',
		category: 'politics',
	},
	{
		name: 'Charles de Gaulle',
		born: 1890,
		died: 1970,
		img: 'De_Gaulle.jpg',
		category: 'politics',
	},
	{
		name: 'Ulysses S. Grant',
		born: 1822,
		died: 1885,
		img: 'Ulysses_S._Grant.jpg',
		category: 'politics',
	},
	{
		name: 'John von Neumann',
		born: 1903,
		died: 1957,
		img: 'JohnvonNeumann.jpg',
		category: 'science',
	},
	{
		name: 'Thomas Edison',
		born: 1847,
		died: 1931,
		img: 'Thomas_Edison.jpg',
		category: 'science',
	},
	{
		name: 'Winston Churchill',
		born: 1874,
		died: 1965,
		img: 'Winston Churchill.jpg',
		category: 'politics',
	},
	{
		name: '&Eacute;variste Galois',
		born: 1811,
		died: 1832,
		img: 'Evariste_galois.jpg',
		category: 'science',
	},
	{
		name: 'Charles Darwin',
		born: 1809,
		died: 1882,
		img: 'Charles Darwin.jpg',
		category: 'science',
	},
	{
		name: 'Gary Cooper',
		born: 1901,
		died: 1961,
		img: 'Gary_Cooper.jpg',
		category: 'arts',
	},
	{
		name: 'John Lennon',
		born: 1940,
		died: 1980,
		img: 'John Lennon.jpg',
		category: 'arts',
	},
	{
		name: 'Woodrow Wilson',
		born: 1856,
		died: 1924,
		img: 'Woodrow_Wilson.jpg',
		category: 'politics',
	},
	{
		name: 'Georges Clemenceau',
		born: 1841,
		died: 1929,
		img: 'Georges_Clemenceau.jpg',
		category: 'politics',
	},
	{
		name: 'Neil Armstrong',
		born: 1930,
		died: 2012,
		img: 'Neil_Armstrong.jpg',
		category: 'explorers',
	},
	{
		name: 'Sir Ernest Henry Shackleton',
		born: 1874,
		died: 1922,
		img: 'Ernest_Shackleton.jpg',
		category: 'explorers',
	},
	{
		name: 'Marilyn Monroe',
		born: 1926,
		died: 1962,
		img: 'Marilyn-Monroe.jpg',
		category: 'arts',
	},
	{
		name: 'Sarah Bernhardt',
		born: 1844,
		died: 1923,
		img: 'Sarah_Bernhardt.jpg',
		category: 'arts',
	},
	{
		name: 'Franz Liszt',
		born: 1811,
		died: 1886,
		img: 'Franz_Liszt.jpg',
		category: 'arts',
	},
	{
		name: 'Fr&eacute;d&eacute;ric Chopin',
		born: 1810,
		died: 1849,
		img: 'Frederic_Chopin.jpeg',
		category: 'arts',
	},
	{
		name: 'Michael Jackson',
		born: 1958,
		died: 2009,
		img: 'Michael Jackson.jpg',
		category: 'arts',
	},
	{
		name: 'Wolfgang Amadeus Mozart',
		born: 1756,
		died: 1791,
		img: 'Mozartl.jpg',
		category: 'arts',
	},
	{
		name: 'Louis Armstrong',
		born: 1901,
		died: 1971,
		img: 'Louis_Armstrong.jpg',
		category: 'arts',
	},
	{
		name: 'Ludwig van Beethoven',
		born: 1770,
		died: 1827,
		img: 'Beethoven.jpg',
		category: 'arts',
	},
	{
		name: 'Camille Saint-Sa&euml;ns',
		born: 1835,
		died: 1921,
		img: 'Saint-Saëns.jpg',
		category: 'arts',
	},
	{
		name: 'Jimi Hendrix',
		born: 1942,
		died: 1970,
		img: 'Jimi Hendrix.jpg',
		category: 'arts',
	},
	{
		name: 'Friedrich Nietzsche',
		born: 1844,
		died: 1900,
		img: 'Nietzsche.jpg',
		category: 'science',
	},
	{
		name: 'Dmitri Mendeleev',
		born: 1834,
		died: 1907,
		img: 'Dmitri Mendeleev.jpg',
		category: 'science',
	},
	{
		name: 'Louis Pasteur',
		born: 1822,
		died: 1895,
		img: 'Louis_Pasteur.jpg',
		category: 'science',
	},
	{
		name: 'James Clerk Maxwell',
		born: 1831,
		died: 1879,
		img: 'James_Clerk_Maxwell.png',
		category: 'science',
	},
	{
		name: 'Guglielmo Marconi',
		born: 1874,
		died: 1937,
		img: 'Guglielmo_Marconi.jpg',
		category: 'science',
	},
	{
		name: 'Michael Faraday',
		born: 1791,
		died: 1867,
		img: 'Michael_Faraday.jpg',
		category: 'science',
	},
	{
		name: 'Salvador Dal&iacute;',
		born: 1904,
		died: 1989,
		img: 'Salvador Dali.jpg',
		category: 'arts',
	},
	{
		name: 'Nathaniel Hawthorne',
		born: 1804,
		died: 1864,
		img: 'Nathaniel_Hawthorne.jpg',
		category: 'arts',
	},
	{
		name: 'Leo Tolstoy',
		born: 1828,
		died: 1910,
		img: 'Leo Tolstoy.jpg',
		category: 'arts',
	},
	{
		name: 'Fyodor Dostoevsky',
		born: 1821,
		died: 1881,
		img: 'Fyodor Dostoevsky.jpg',
		category: 'arts',
	},
	{
		name: 'Chiang Kai-shek',
		born: 1887,
		died: 1975,
		img: 'Chiang_Kai-shek.jpg',
		category: 'politics',
	},
	{
		name: 'Christopher Columbus',
		born: 1451,
		died: 1506,
		img: 'Christopher_Columbus.jpg',
		category: 'explorers',
	},
	{
		name: 'Marco Polo',
		born: 1254,
		died: 1324,
		img: 'Marco_Polo.jpg',
		category: 'explorers',
	},
	{
		name: 'Ferdinand Magellan',
		born: 1480,
		died: 1521,
		img: 'Ferdinand_Magellan.jpg',
		category: 'explorers',
	},
	{
		name: 'Leonardo da Vinci',
		born: 1452,
		died: 1519,
		img: 'Leonardo_da_Vinci.jpg',
		category: 'arts',
	},
	{
		name: 'William Shakespeare',
		born: 1564,
		died: 1616,
		img: 'William_Shakespeare.jpg',
		category: 'arts',
	},
	{
		name: 'Edwin Hubble',
		born: 1889,
		died: 1953,
		category: 'arts',
	},
	{
		name: 'Pierre de Fermat',
		born: 1607,
		died: 1655,
		category: 'science',
	},
	{
		name: 'Immanuel Kant',
		born: 1724,
		died: 1804,
		img: 'Immanuel_Kant.jpg',
		category: 'philosophy',
	},
	{
		name: 'Friedrich Nietzsche',
		born: 1844,
		died: 1900,
		img: 'Friedrich_Nietzsche.jpg',
		category: 'philosophy',
	},
	{
		name: 'Ren&eacute; Descartes',
		born: 1596,
		died: 1650,
		img: 'Rene_Descartes.jpg',
		category: 'philosophy',
	},
	{
		name: 'John Locke',
		born: 1632,
		died: 1704,
		img: 'John_Locke.jpg',
		category: 'philosophy',
	},
	{
		name: 'David Hume',
		born: 1711,
		died: 1776,
		img: 'David_Hume.jpg',
		category: 'philosophy',
	},
	{
		name: 'Karl Marx',
		born: 1818,
		died: 1883,
		img: 'Karl_Marx.jpg',
		category: 'philosophy',
	},
	{
		name: 'Jean-Jacques Rousseau',
		born: 1712,
		died: 1778,
		img: 'Jean-Jacques_Rousseau.jpg',
		category: 'philosophy',
	},
	{
		name: 'Baruch Spinoza',
		born: 1632,
		died: 1677,
		img: 'Baruch_Spinoza.jpg',
		category: 'philosophy',
	},
	{
		name: 'Georg Wilhelm Friedrich Hegel',
		born: 1770,
		died: 1831,
		img: 'Georg_Wilhelm_Friedrich_Hegel.jpg',
		category: 'philosophy',
	},
	{
		name: 'Arthur Schopenhauer',
		born: 1788,
		died: 1860,
		img: 'Arthur_Schopenhauer.jpg',
		category: 'philosophy',
	},
	{
		name: 'S&oslash;ren Kierkegaard',
		born: 1813,
		died: 1855,
		img: 'Soren_Kierkegaard.jpg',
		category: 'philosophy',
	},
	{
		name: 'Simone de Beauvoir',
		born: 1908,
		died: 1986,
		img: 'Simone_de_Beauvoir.jpg',
		category: 'philosophy',
	},
	{
		name: 'Michel Foucault',
		born: 1926,
		died: 1984,
		img: 'Michel_Foucault.jpg',
		category: 'philosophy',
	},
	{
		name: 'Bertrand Russell',
		born: 1872,
		died: 1970,
		category: 'philosophy',
	},
	{
		name: 'Ludwig Wittgenstein',
		born: 1889,
		died: 1951,
		category: 'philosophy',
	},
	{
		name: 'Thomas Aquinas',
		born: 1225,
		died: 1274,
		category: 'philosophy',
	},
	{
		name: 'Thomas Hobbes',
		born: 1588,
		died: 1679,
		category: 'philosophy',
	},
	{
		name: 'John Stuart Mill',
		born: 1806,
		died: 1873,
		category: 'philosophy',
	},
	{
		name: 'William James',
		born: 1842,
		died: 1910,
		category: 'philosophy',
	},
	{
		name: 'Jean-Paul Sartre',
		born: 1905,
		died: 1980,
		category: 'philosophy',
	},
	{
		name: 'Albert Camus',
		born: 1913,
		died: 1960,
		category: 'philosophy',
	},
];
