const data = [
	{
		name: 'Albert Einstein',
		born: 1879,
		died: 1955,
		img: 'Albert Einstein.jpg',
		category: 'science',
	},
	{
		name: 'Benjamin Franklin',
		born: 1706,
		died: 1790,
		img: 'Benjamin Franklin.jpg',
		category: 'politics',
	},
	{
		name: 'Kurt G&ouml;del',
		born: 1906,
		died: 1978,
		img: 'Kurt_godel.jpg',
		category: 'science',
	},
	{
		name: 'Franz Kafka',
		born: 1883,
		died: 1924,
		img: 'Franz_Kafka.jpg',
		category: 'writers',
	},
	{
		name: 'Amelia Earhart',
		born: 1897,
		died: 1939,
		img: 'Amelia_Earhart.jpg',
		category: 'explorers',
	},
	{
		name: 'Charlie Chaplin',
		born: 1889,
		died: 1977,
		img: 'Charlie_Chaplin.jpg',
		category: 'arts',
	},
	{
		name: 'Nikola Tesla',
		born: 1856,
		died: 1943,
		img: 'Nikola Tesla.jpeg',
		category: 'science',
	},
	{
		name: 'Igor Stravinsky',
		born: 1882,
		died: 1971,
		img: 'Igor_Stravinsky.jpg',
		category: 'arts',
	},
	{
		name: 'Ernest Hemingway',
		born: 1899,
		died: 1961,
		img: 'hemingway-800x800.jpg',
		category: 'arts',
	},
	{
		name: 'Tennessee Williams',
		born: 1911,
		died: 1983,
		img: 'Tennessee_Williams.jpgs',
		category: 'arts',
	},
	{
		name: 'George Orwell',
		born: 1903,
		died: 1950,
		img: 'George_Orwell.jpg',
		category: 'arts',
	},
	{
		name: 'Jane Austen',
		born: 1775,
		died: 1817,
		img: 'Jane-Austen.jpg',
		category: 'arts',
	},
	// {
	// 	name: '',
	// 	born: 0,
	// 	died: 0,
	// 	img: '',
	// 	category: 'arts',
	// },
	// {
	// 	name: '',
	// 	born: 0,
	// 	died: 0,
	// 	img: '',
	// 	category: 'arts',
	// },
	// {
	// 	name: '',
	// 	born: 0,
	// 	died: 0,
	// 	img: '',
	// 	category: 'arts',
	// },
	// {
	// 	name: '',
	// 	born: 0,
	// 	died: 0,
	// 	img: '',
	// 	category: 'arts',
	// },
	// {
	// 	name: '',
	// 	born: 0,
	// 	died: 0,
	// 	img: '',
	// 	category: 'arts',
	// },
	// {
	// 	name: '',
	// 	born: 0,
	// 	died: 0,
	// 	img: '',
	// 	category: 'arts',
	// },
];
